# Generated by Django 3.2.8 on 2021-10-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_turistico', '0006_alter_pontoturistico_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
