# Generated by Django 3.2.8 on 2021-10-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
